### PR TITLE
49 htm lsearch area

### LINKED ISSUE #49: HTML search area
- move food search where time is and replace time with a carousel of food photos and help comments?

### PR DESCRIPTION
**Pull request by dianecandler**
Finished cleaning up HTML for now.  Modified price buttons and moved selection items so transportation is followed by price then added a new carousel instead of the wristwatch.

closes #49

### CODE REVIEW

**Comment by dianecandler** [comment]
Please approve changes to this branch so we can merge and close the branch.

**Comment by dianecandler** [comment]
Added all to this branch review.  Please approve or let me know if you have questions.  Thank you!

closes #50

**Review by marlon20m — DISMISSED** [review]
Changes approved

**Review by chong0810 — DISMISSED** [review]

**Review by adrian-palacios — DISMISSED** [review]

**Review by chong0810 — DISMISSED** [review]
Good job!

**Review by adrian-palacios — DISMISSED** [review]

**Review by chong0810 — APPROVED** [review]
Awesome work team

**Review by adrian-palacios — APPROVED** [review]
Great job!

**Review by dianecandler — COMMENTED** [review]
Approve these updates and edits!  Great job

**Review by marlon20m — APPROVED** [review]
We are finishing this! great Job everyone!

**Pull request merged**
