### PR TITLE
initial commit and testing for direction API

### PR DESCRIPTION
**Pull request by chong0810**
Attempt to fix the CORB issue for requesting JSON from google maps API

### CODE REVIEW

**Review by marlon20m — COMMENTED** [review]
YES I APPROVE

**Review by adrian-palacios — APPROVED** [review]
I approve

**Review by marlon20m — APPROVED** [review]
APPROVE!

**Review by dianecandler — APPROVED** [review]
Approving modifications to update CSS links, test JS for Google Maps

**Pull request merged**
