### PR TITLE
54 lessons learned

### PR DESCRIPTION
**Pull request by dianecandler**
Thank you for handling this!

### CODE REVIEW

**Comment by dianecandler** [comment]
All set...thank you!

**Comment by dianecandler** [comment]
Finished updating image file list and added presentation plus files into this directory that were used in the readme.  Updated readme and formated for easy viewing.  Lots of visual enhancements.  Moved meeting note content to the Agile.md file with the rest of the meeting notes.

**Comment by dianecandler** [comment]
closes #55

**Review by chong0810 — APPROVED** [review]

**Review by chong0810 — APPROVED** [review]

**Review by adrian-palacios — APPROVED** [review]

**Comment by dianecandler** [comment]
resolved #55

**Review by marlon20m — APPROVED** [review]
Great Job !

**Comment by dianecandler** [comment]
closes #56

**Pull request closed without merging**
