### PR TITLE
adding a Logo mockup in the Readme

### LINKED ISSUE #22: Logo Mock-up for Food Truck
Add to Readme.md

### PR DESCRIPTION
**Pull request by marlon20m**
Adding a logo mock up to the Readme for the food truck. This is for reference. Logo will be in the images folder.

closes #22

### CODE REVIEW

**Review by adrian-palacios — APPROVED** [review]
artistic

**Comment by dianecandler** [comment]
Love the drawing

**Review by chong0810 — APPROVED** [review]
Great work!

**Review by dianecandler — APPROVED** [review]
Added details and summary on lines 178.

**Comment by dianecandler** [comment]
closes #23

**Comment by dianecandler** [comment]
closes #23

**Pull request merged**
