### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dianecandler**
Changed information from destinATX to FoodTrucksATX and added some details including APIs

### CODE REVIEW

**Review by adrian-palacios — APPROVED** [review]
Approved

**Review by chong0810 — APPROVED** [review]
Approved! Thanks Diane

**Comment by adrian-palacios** [comment]
Awesome work!!!

**Comment by dianecandler** [comment]
Please review and approve changes to this Readme.md update.  I've changed content to reflect FoodTrucksATX versus destinATX.  Thank you!

**Comment by dianecandler** [comment]
All approved so ready to merge and delete branch.

**Review by marlon20m — APPROVED** [review]

**Pull request merged**
